### ISSUE TITLE
不行啊，不能签到

### ISSUE THREAD

**Issue by Bob-Yuan** [daimiaopeng/IthomeQianDao#2]

**Comment by daimiaopeng** [comment]
明明可以签到，加我qq：844362911聊

**Comment by Bob-Yuan** [comment]
> 明明可以签到，加我qq：844362911聊

看了一下代码，可能是代码第10行的网址没使用https导致的，改成    url_login = 'https://my.ruanmei.com/Default.aspx/LoginUser'后可以了

**Comment by daimiaopeng** [comment]
我就是用这个代码天天签到的，没看到断签。
 
---原始邮件---
发件人: "袁博"<notifications@github.com>
发送时间: 2019年5月17日(星期五) 下午5:27
收件人: "daimiaopeng/ithome_qiandao"<ithome_qiandao@noreply.github.com>;
抄送: "daimiaopeng"<844362911@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [daimiaopeng/ithome_qiandao] 不行啊，不能签到 (#2)


 
明明可以签到，加我qq：844362911聊
  
看了一下代码，可能是代码第10行的网址没使用https导致的，改成    url_login = 'https://my.ruanmei.com/Default.aspx/LoginUser'后可以了

**Comment by Bob-Yuan** [comment]
> 我就是用这个代码天天签到的，没看到断签。
> […](#)
> ---原始邮件--- 发件人: "袁博"<notifications@github.com> 发送时间: 2019年5月17日(星期五) 下午5:27 收件人: "daimiaopeng/ithome_qiandao"<ithome_qiandao@noreply.github.com>; 抄送: "daimiaopeng"<844362911@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [daimiaopeng/ithome_qiandao] 不行啊，不能签到 (#2) 明明可以签到，加我qq：844362911聊 看了一下代码，可能是代码第10行的网址没使用https导致的，改成 url_login = '[https://my.ruanmei.com/Default.aspx/LoginUser'后可以了](https://my.ruanmei.com/Default.aspx/LoginUser'%E5%90%8E%E5%8F%AF%E4%BB%A5%E4%BA%86) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

可能是我是第一次登录，没有cookie，我改成https成功登录一次后，再改回http也可以登录了，不过第一次的时候确实不行

**Comment by daimiaopeng** [comment]
不管了，反正可以用就行了


 
---原始邮件---
发件人: "袁博"<notifications@github.com>
发送时间: 2019年5月17日(星期五) 下午5:55
收件人: "daimiaopeng/ithome_qiandao"<ithome_qiandao@noreply.github.com>;
抄送: "daimiaopeng"<844362911@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [daimiaopeng/ithome_qiandao] 不行啊，不能签到 (#2)


 
我就是用这个代码天天签到的，没看到断签。
 …
 ---原始邮件--- 发件人: "袁博"notifications@github.com 发送时间: 2019年5月17日(星期五) 下午5:27 收件人: "daimiaopeng/ithome_qiandao"ithome_qiandao@noreply.github.com; 抄送: "daimiaopeng"844362911@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [daimiaopeng/ithome_qiandao] 不行啊，不能签到 (#2) 明明可以签到，加我qq：844362911聊 看了一下代码，可能是代码第10行的网址没使用https导致的，改成 url_login = 'https://my.ruanmei.com/Default.aspx/LoginUser'后可以了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
可能是我是第一次登录，没有cookie，我改成https成功登录一次后，再改回http也可以登录了，不过第一次的时候确实不行
